server:
  port: 8443
  ssl:
    enabled: false
    key-store-type: PKCS12
    key-store: classpath:ssl/keystore.p12
    key-store-password: password
    key-alias: springboot

  servlet:
    context-path: /api/v1

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: azzadal
    password: brZ72z9NqcPT5yjNqhrBnKcKE98gCe3R
    url: jdbc:postgresql://dpg-cmmuohi1hbls73ci9fo0-a.frankfurt-postgres.render.com:5432/autocenter
  liquibase:
    change-log: classpath:liquibase/changelog/master.yml
    enabled: true
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        globally_quoted_identifiers: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
hibernate:
  jdbc:
    time_zone: UTC
jwt:
  secret: very-very-secret-string
  expiration: 86400