databaseChangeLog:
  - objectQuotingStrategy: QUOTE_ALL_OBJECTS
  - changeSet:
      id: schema/user/table
      author: kvasov_andrey
      changes:
        - createTable:
            columns:
              - column:
                  autoIncrement: true
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: USERPK
                  name: id
                  type: BIGINT
              - column:
                  constraints:
                    nullable: false
                  name: login
                  type: VARCHAR(255)
              - column:
                  name: password
                  type: VARCHAR(255)
              - column:
                  name: FIO
                  type: VARCHAR(255)
              - column:
                  name: birthday
                  type: date
              - column:
                  name: email
                  type: VARCHAR(255)
              - column:
                  name: address
                  type: VARCHAR(255)
              - column:
                  name: telefon
                  type: VARCHAR(255)
              - column:
                  name: role_id
                  type: BIGINT
            tableName: Usr
  - changeSet:
      id: schema/role/table
      author: kvasov_andrey
      changes:
        - createTable:
            columns:
              - column:
                  autoIncrement: true
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: USER_ROLEPK
                  name: id
                  type: BIGINT
              - column:
                  name: name
                  type: VARCHAR(255)
            tableName: user_role
  - changeSet:
      id: schema/car/table
      author: kvasov_andrey
      changes:
        - createTable:
            columns:
              - column:
                  autoIncrement: true
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: CARPK
                  name: id
                  type: BIGINT
              - column:
                  name: mark_id
                  type: BIGINT
              - column:
                  name: model_id
                  type: BIGINT
              - column:
                  name: color
                  type: VARCHAR(255)
              - column:
                  name: status
                  type: VARCHAR(255)
            tableName: Car
  - changeSet:
      id: schema/mark/table
      author: kvasov_andrey
      changes:
        - createTable:
            columns:
              - column:
                  autoIncrement: true
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: MARKPK
                  name: id
                  type: BIGINT
              - column:
                  name: name
                  type: VARCHAR(255)
            tableName: Mark
  - changeSet:
      id: schema/model/table
      author: kvasov_andrey
      changes:
        - createTable:
            columns:
              - column:
                  autoIncrement: true
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: MODELPK
                  name: id
                  type: BIGINT
              - column:
                  name: name
                  type: VARCHAR(255)
            tableName: Model
  - changeSet:
      id: schema/test-drive-request/table
      author: kvasov_andrey
      changes:
        - createTable:
            columns:
              - column:
                  autoIncrement: true
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: TEST_DRIVE_PK
                  name: id
                  type: BIGINT
              - column:
                  name: car_id
                  type: BIGINT
              - column:
                  name: user_id
                  type: BIGINT
              - column:
                  name: testDriveDate
                  type: DATE
              - column:
                  name: connection
                  type: VARCHAR(255)
            tableName: Test_drive_request
  - changeSet:
      id: schema/carsharing-request/table
      author: kvasov_andrey
      changes:
        - createTable:
            columns:
              - column:
                  autoIncrement: true
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: CARSHARING_PK
                  name: id
                  type: BIGINT
              - column:
                  name: car_id
                  type: BIGINT
              - column:
                  name: user_id
                  type: BIGINT
              - column:
                  name: connection
                  type: VARCHAR(255)
            tableName: Carsharing_request
  - changeSet:
      id: schema/trade-in-request/table
      author: kvasov_andrey
      changes:
        - createTable:
            columns:
              - column:
                  autoIncrement: true
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: TRADE_IN_PK
                  name: id
                  type: BIGINT
              - column:
                  name: user_id
                  type: BIGINT
              - column:
                  name: connection
                  type: VARCHAR(255)
            tableName: Trade_in_request
  - changeSet:
      id: schema/repair-service-request/table
      author: kvasov_andrey
      changes:
        - createTable:
            columns:
              - column:
                  autoIncrement: true
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: REPAIR_SERVICE_PK
                  name: id
                  type: BIGINT
              - column:
                  name: user_id
                  type: BIGINT
              - column:
                  name: auto
                  type: VARCHAR(255)
              - column:
                  name: serviceType
                  type: VARCHAR(255)
            tableName: Repair_service
############################# связи #############################
  - changeSet:
      id: schema/user/foreign-key/fk_user_role_id
      author: kvasov_andrey
      changes:
        - addForeignKeyConstraint:
            baseColumnNames: role_id
            baseTableName: Usr
            constraintName: UR_FK_USER_ROLE_ID
            deferrable: false
            initiallyDeferred: false
            referencedColumnNames: id
            referencedTableName: user_role
            validate: true
            onDelete: cascade
  - changeSet:
      id: schema/car/foreign-key/fk_car_mark_id
      author: kvasov_andrey
      changes:
        - addForeignKeyConstraint:
            baseColumnNames: mark_id
            baseTableName: Car
            constraintName: CM_FK_CAR_MARK_ID
            deferrable: false
            initiallyDeferred: false
            referencedColumnNames: id
            referencedTableName: Mark
            validate: true
            onDelete: cascade
  - changeSet:
      id: schema/car/foreign-key/fk_car_model_id
      author: kvasov_andrey
      changes:
        - addForeignKeyConstraint:
            baseColumnNames: model_id
            baseTableName: Car
            constraintName: CM_FK_CAR_MODEL_ID
            deferrable: false
            initiallyDeferred: false
            referencedColumnNames: id
            referencedTableName: Model
            validate: true
            onDelete: cascade
  - changeSet:
      id: schema/test_drive/foreign-key/fk_car_id
      author: kvasov_andrey
      changes:
        - addForeignKeyConstraint:
            baseColumnNames: car_id
            baseTableName: Test_drive_request
            constraintName: TD_FK_CAR_ID
            deferrable: false
            initiallyDeferred: false
            referencedColumnNames: id
            referencedTableName: Car
            validate: true
            onDelete: cascade
  - changeSet:
      id: schema/test_drive/foreign-key/fk_user_id
      author: kvasov_andrey
      changes:
        - addForeignKeyConstraint:
            baseColumnNames: user_id
            baseTableName: Test_drive_request
            constraintName: TD_FK_USER_ID
            deferrable: false
            initiallyDeferred: false
            referencedColumnNames: id
            referencedTableName: Usr
            validate: true
            onDelete: cascade
  - changeSet:
      id: schema/trade_in/foreign-key/fk_user_id
      author: kvasov_andrey
      changes:
        - addForeignKeyConstraint:
            baseColumnNames: user_id
            baseTableName: Test_drive_request
            constraintName: TI_FK_USER_ID
            deferrable: false
            initiallyDeferred: false
            referencedColumnNames: id
            referencedTableName: Usr
            validate: true
            onDelete: cascade
  - changeSet:
      id: schema/carsharing/foreign-key/fk_user_id
      author: kvasov_andrey
      changes:
        - addForeignKeyConstraint:
            baseColumnNames: user_id
            baseTableName: Carsharing_request
            constraintName: CSH_FK_USER_ID
            deferrable: false
            initiallyDeferred: false
            referencedColumnNames: id
            referencedTableName: Usr
            validate: true
            onDelete: cascade
  - changeSet:
      id: schema/carsharing/foreign-key/fk_car_id
      author: kvasov_andrey
      changes:
        - addForeignKeyConstraint:
            baseColumnNames: car_id
            baseTableName: Carsharing_request
            constraintName: CSH_FK_CAR_ID
            deferrable: false
            initiallyDeferred: false
            referencedColumnNames: id
            referencedTableName: Car
            validate: true
            onDelete: cascade
  - changeSet:
      id: schema/repair-service/foreign-key/fk_user_id
      author: kvasov_andrey
      changes:
        - addForeignKeyConstraint:
            baseColumnNames: user_id
            baseTableName: Repair_service
            constraintName: RSR_FK_USER_ID
            deferrable: false
            initiallyDeferred: false
            referencedColumnNames: id
            referencedTableName: Usr
            validate: true
            onDelete: cascade
  - changeSet:
      id: schema/user/unique_constraint/login
      author: kvasov_andrey
      changes:
        - addUniqueConstraint:
            columnNames: 'login'
            constraintName: USR_LOGIN
            tableName: Usr
